---
on:
  schedule:
    - cron: '30 5 * * 1,3'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-cms-tutorial:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run the workflow
        run: echo "not implemented"